trigger:
 - main

pool:
   vmImage: 'ubuntu-20.04'

variables:
- group: context

steps:

- task: SystemsManagerGetParameter@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    readMode: 'single'
    parameterName: 'bucketCloudfront'
    parameterVersion: '1'

- task: SystemsManagerGetParameter@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    readMode: 'single'
    parameterName: 'bucketSourceCode'
    parameterVersion: '1'


- task: SystemsManagerGetParameter@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    readMode: 'single'
    parameterName: 'postFunctionName'
    parameterVersion: '1'

- task: SystemsManagerGetParameter@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    readMode: 'single'
    parameterName: 'putFunctionName'
    parameterVersion: '1'
- task: SystemsManagerGetParameter@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    readMode: 'single'
    parameterName: 'getFunctionName'
    parameterVersion: '1'

- task: SystemsManagerGetParameter@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    readMode: 'single'
    parameterName: 'deleteFunctionName'
    parameterVersion: '1'

- script: |
    echo '$(deleteFunctionName)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install -g @angular/cli
  displayName: 'Install Angular CLI'

- script: ng config -g cli.warnings.versionMismatch false
  displayName: 'Disable Angular CLI version mismatch warning'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/frontend/angular-app'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ng build --configuration=production
    workingDirectory: '$(System.DefaultWorkingDirectory)/frontend/angular-app'

- task: S3Upload@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    bucketName: '$(BucketNameCloudFront)'
    sourceFolder: '$(System.DefaultWorkingDirectory)/frontend/angular-app/dist/angular-app'
    globExpressions: '**'

- script: |
    sudo apt-get install zip -y
    cd $(System.DefaultWorkingDirectory)/backend/
    zip -r $(Build.StagingDirectory)/$(ObjectName) .
  displayName: 'Compress backend folder into zip'


- task: S3Upload@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    bucketName: '$(BucketNameCode)'
    sourceFolder: '$(Build.StagingDirectory)'
    globExpressions: '$(ObjectName)'

- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    deploymentMode: 'codeonly'
    functionName: '$(GetFunctionName)'
    codeLocation: 's3object'
    s3Bucket: '$(BucketNameCode)'
    s3ObjectKey: '$(ObjectName)'

- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    deploymentMode: 'codeonly'
    functionName: '$(PostFunctionName)'
    codeLocation: 's3object'
    s3Bucket: '$(BucketNameCode)'
    s3ObjectKey: '$(ObjectName)'

- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    deploymentMode: 'codeonly'
    functionName: '$(DeleteFunctionName)'
    codeLocation: 's3object'
    s3Bucket: '$(BucketNameCode)'
    s3ObjectKey: '$(ObjectName)'

- task: LambdaDeployFunction@1
  inputs:
    awsCredentials: 'AWSConnection'
    regionName: '$(region)'
    deploymentMode: 'codeonly'
    functionName: '$(PutFunctionName)'
    codeLocation: 's3object'
    s3Bucket: '$(BucketNameCode)'
    s3ObjectKey: '$(ObjectName)'