trigger:
 - main

pool:
   vmImage: 'ubuntu-20.04'

variables:
- group: prueba_variables

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $(bucket-source-code)

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      env
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(System.DefaultWorkingDirectory)/frontend/angular-app/'
    customCommand: 'run build -- --url=$(url)'

