trigger:
 - main

pool:
   vmImage: 'ubuntu-20.04'

variables:
- group: prueba_variables

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $(bucket-source-code)

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      env

- script: npm install -g @angular/cli
  displayName: 'Install Angular CLI'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install @angular-devkit/build-angular --save-dev'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build -- --prod'
    workingDir: '$(System.DefaultWorkingDirectory)/frontend/angular-app'
  displayName: 'Build Angular App'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/frontend/angular-app/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/angular-app'
  displayName: 'Copy Angular App artifacts'