trigger:
 - main

pool:
   vmImage: 'ubuntu-20.04'

variables:
   group: prueba_variables

steps:

- task: PowerShell@2
  displayName: 'Show Environment Variables'
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem Env:


